# ============================================================================
# clash 覆写文件 轻量
# 仓库 https://github.com/RikkaSaiko1/clash_config
#
# - DNS 防泄漏: fake-ip + 全 DoH, nameserver-policy 分组, 出口分离
# - 轻量规则集: 精简策略组 + 精简规则链 + 裁剪 rule-providers

tun!:
  enable: true
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  route-exclude-address-set:
    - cn_ip

sniffer!:
  enable: true
  override-destination: false
  force-dns-mapping: false
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

# ============================================================================
# DNS
# ============================================================================
dns!:
  enable: true
  cache-algorithm: arc
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-ttl: 1
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter-mode: blacklist
  default-nameserver:
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

  nameserver-policy:
    "rule-set:cn,private,fakeipfilter_cn,games_cn,microsoft_cn,apple_cn":
    - https://dns.alidns.com/dns-query#disable-qtype-65=true
    - https://doh.pub/dns-query#disable-qtype-65=true
    "rule-set:fakeipfilter_!cn":
    - https://8.8.8.8/dns-query#PROXY&disable-qtype-65=true
  nameserver:
    - https://8.8.8.8/dns-query#PROXY&ecs=223.5.5.0/24
  fallback:
    - https://8.8.8.8/dns-query#PROXY
  fallback-filter:
    geoip: true
    geoip-code: CN
  fake-ip-filter:
    - rule-set:fakeipfilter_cn
    - rule-set:fakeipfilter_!cn
    - rule-set:private
    - rule-set:cn
    - rule-set:microsoft_cn
    - rule-set:apple_cn
    - rule-set:games_cn




# 策略组通用配置
group_common:
  group_common_select:
    &group_common_select {type: select,interval: 300,timeout: 1500,max-failed-times: 5,empty-fallback: REJECT,url: 'https://www.apple.com/library/test/success.html',lazy: true}

  group_common_auto:
    &group_common_auto {type: url-test,interval: 60,timeout: 1500,max-failed-times: 5,empty-fallback: REJECT,url: 'https://www.apple.com/library/test/success.html',lazy: true,tolerance: 50,include-all: true,exclude-type: 'DIRECT'}


# 通用代理节点组
proxies_common:  # 通用代理节点组
  proxies_default:
    &proxies_default {proxies: ['PROXY','AUTO','HK Group','SG Group','JP Group','US Group','TW Group','KR Group','Other Group']}

  proxies_direct:
    &proxies_direct {proxies: ['PROXY','AUTO','HK Group','SG Group','JP Group','US Group','TW Group','KR Group','Other Group','DIRECT']}

  proxies_AI:
    &proxies_AI {proxies: ['PROXY','SG Group','JP Group','US Group','KR Group',]}
  
  proxies_proxy:
    &proxies_proxy {proxies: ['AUTO','HK Group','JP Group','US Group','SG Group','TW Group','KR Group','Other Group']}


# 地区过滤器正则表达式定义
group_filter:

  HK_filter:
    &HK_filter {filter: '(?i)(🇭🇰|香港|(?<![A-Za-z])HKG?(?![A-Za-z])|hong\s*kong)'}

  JP_filter:
    &JP_filter {filter: '(?i)(🇯🇵|日本|东京|大阪|京都|(?<![A-Za-z])JPN?(?![A-Za-z])|japan)'}

  US_filter:
    &US_filter {filter: '(?i)(🇺🇸|美国|纽约|洛杉矶|旧金山|芝加哥|休斯顿|迈阿密|西雅图|波士顿|华盛顿|拉斯维加斯|圣何塞|圣地亚哥|(?<![A-Za-z])USA?(?![A-Za-z])|america|united\s*states)'}

  SG_filter:
    &SG_filter {filter: '(?i)(🇸🇬|新加坡|狮城|(?<![A-Za-z])SGP?(?![A-Za-z])|singapore)'}

  TW_filter:
    &TW_filter {filter: '(?i)(🇹🇼|台湾|台北|高雄|(?<![A-Za-z])TWN?(?![A-Za-z])|taiwan)'}

  KR_filter:
    &KR_filter {filter: '(?i)(🇰🇷|韩国|首尔|釜山|仁川|大邱|(?<![A-Za-z])KOR?(?![A-Za-z])|korea|south\s*korea)'}

  exclude_filter:
    &exclude_filter {exclude-filter: '(?i)(🇭🇰|香港|(?<![A-Za-z])HKG?(?![A-Za-z])|hong\s*kong|🇯🇵|日本|东京|大阪|京都|(?<![A-Za-z])JPN?(?![A-Za-z])|japan|🇺🇸|美国|纽约|洛杉矶|旧金山|芝加哥|休斯顿|迈阿密|西雅图|波士顿|华盛顿|拉斯维加斯|圣何塞|圣地亚哥|(?<![A-Za-z])USA?(?![A-Za-z])|america|united\s*states|🇸🇬|新加坡|狮城|(?<![A-Za-z])SGP?(?![A-Za-z])|singapore|🇹🇼|台湾|台北|高雄|(?<![A-Za-z])TWN?(?![A-Za-z])|taiwan|🇰🇷|韩国|首尔|釜山|仁川|大邱|(?<![A-Za-z])KOR?(?![A-Za-z])|korea|south\s*korea)',exclude-type: 'DIRECT'}


# 定义分流策略组
proxy-groups:  # 定义分流策略组

  - name: 'PROXY'
    <<: [*group_common_select, *proxies_proxy]
    include-all-proxies: true
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/Static.png'

  - name: 'AUTO'
    <<: *group_common_auto
    hidden: false
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/Roundrobin.png'

  - name: 'YouTube'
    <<: [*group_common_select, *proxies_default]
    icon: 'https://cdn.jsdelivr.net/gh/RikkaSaiko1/clash_config@main/svg/youtube.svg'

  # Google FCM
  - name: 'Google'
    <<: [*group_common_select, *proxies_default]
    icon: 'https://cdn.jsdelivr.net/gh/RikkaSaiko1/clash_config@main/svg/google.svg'

  - name: 'AI'
    <<: [*group_common_select, *proxies_AI]
    default-selected: 'US Group'
    icon: 'https://cdn.jsdelivr.net/gh/RikkaSaiko1/clash_config@main/svg/deepseek.svg'

  - name: 'Telegram'
    <<: [*group_common_select, *proxies_default]
    icon: 'https://cdn.jsdelivr.net/gh/RikkaSaiko1/clash_config@main/svg/telegram.svg'

  - name: 'Twitter'
    <<: [*group_common_select, *proxies_default]
    icon: 'https://cdn.jsdelivr.net/gh/RikkaSaiko1/clash_config@main/svg/twitter.svg'

  ### 地区策略组

  - name: 'HK Group'
    <<: [*group_common_select, *HK_filter]
    include-all: true
    proxies: ['HK Auto Group']
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/HK.png'

  - name: 'HK Auto Group'
    <<: [*group_common_auto, *HK_filter]
    hidden: true

  - name: 'JP Group'
    <<: [*group_common_select, *JP_filter]
    include-all: true
    proxies: ['JP Auto Group']
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/JP.png'

  - name: 'JP Auto Group'
    <<: [*group_common_auto, *JP_filter]
    hidden: true

  - name: 'US Group'
    <<: [*group_common_select, *US_filter]
    include-all: true
    proxies: ['US Auto Group']
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/US.png'

  - name: 'US Auto Group'
    <<: [*group_common_auto, *US_filter]
    hidden: true

  - name: 'SG Group'
    <<: [*group_common_select, *SG_filter]
    include-all: true
    proxies: ['SG Auto Group']
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/SG.png'

  - name: 'SG Auto Group'
    <<: [*group_common_auto, *SG_filter]
    hidden: true

  - name: 'TW Group'
    <<: [*group_common_select, *TW_filter]
    include-all: true
    proxies: ['TW Auto Group']
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/TW.png'

  - name: 'TW Auto Group'
    <<: [*group_common_auto, *TW_filter]
    hidden: true

  - name: 'KR Group'
    <<: [*group_common_select, *KR_filter]
    include-all: true
    proxies: ['KR Auto Group']
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/KR.png'

  - name: 'KR Auto Group'
    <<: [*group_common_auto, *KR_filter]
    hidden: true

  ## 其他地区
  - name: 'Other Group'
    <<: [*group_common_select, *exclude_filter]
    include-all: true
    proxies: ['Other Auto Group']
    icon: 'https://cdn.jsdelivr.net/gh/Orz-3/mini@master/Color/Global.png'

  - name: 'Other Auto Group'
    <<: [*group_common_auto, *exclude_filter]
    hidden: true

rules:
  # 私有网络直连
  - RULE-SET,private,DIRECT
  - RULE-SET,private_ip,DIRECT,no-resolve
  # 国内直连
  - RULE-SET,geolocation-cn,DIRECT
  - RULE-SET,games_cn,DIRECT # 已包含 steam 下载域名
  - RULE-SET,epicgames,DIRECT
  - RULE-SET,nvidia_cn,DIRECT
  - RULE-SET,apple_cn,DIRECT
  - RULE-SET,microsoft_cn,DIRECT
  - DOMAIN,fsend.cn,DIRECT
  - DOMAIN,international-gfe.download.nvidia.com,DIRECT
  # 拦截 STUN/TURN 探测（3478-3481 STUN/TURN、5349 STUN-over-TLS、19302-19309 Google STUN）
  - AND,((NETWORK,UDP),(OR,((DST-PORT,3478-3481),(DST-PORT,5349),(DST-PORT,19302-19309)))),REJECT
  # 禁用国外 QUIC 流量
  - AND,((NETWORK,UDP),(DST-PORT,443),(NOT,((OR,((RULE-SET,cn_additional),(RULE-SET,cn_ip,no-resolve)))))),REJECT
  # 广告拦截
  - RULE-SET,adblockmihomolite,REJECT

  # 代理规则
  - RULE-SET,youtube,YouTube
  - RULE-SET,googlefcm,DIRECT
  - RULE-SET,google,Google
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,ai,AI
  - RULE-SET,telegram,Telegram
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,twitter,Twitter
  - RULE-SET,twitter_ip,Twitter,no-resolve

  # 兜底规则
  - RULE-SET,geolocation-!cn,PROXY
  - RULE-SET,cn_ip,DIRECT
  - MATCH,PROXY

# Rule Provider 通用配置
rule_providers_common:
  rule_providers_domain: &rule_providers_domain { type: http, format: mrs, interval: 86400, behavior: domain }
  rule_providers_ip: &rule_providers_ip { type: http, format: mrs, interval: 86400, behavior: ipcidr }

# 定义 Rule Providers
rule-providers:
  # --- 直连规则集 ---
  private:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/private.mrs'
    path: './ruleset/private.mrs'
    path-in-bundle: 'geo/geosite/private.mrs'

  private_ip:
    <<: *rule_providers_ip
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geoip/private.mrs'
    path: './ruleset/private_ip.mrs'
    path-in-bundle: 'geo/geoip/private.mrs'

  games_cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/category-games@cn.mrs'
    path: './ruleset/category-games@cn.mrs'
    path-in-bundle: 'geo/geosite/category-games@cn.mrs'

  epicgames:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/epicgames.mrs'
    path: './ruleset/epicgames.mrs'
    path-in-bundle: 'geo/geosite/epicgames.mrs'

  nvidia_cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/nvidia@cn.mrs'
    path: './ruleset/nvidia@cn.mrs'
    path-in-bundle: 'geo/geosite/nvidia@cn.mrs'

  apple_cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/apple@cn.mrs'
    path: './ruleset/apple@cn.mrs'
    path-in-bundle: 'geo/geosite/apple@cn.mrs'

  microsoft_cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/microsoft@cn.mrs'
    path: './ruleset/microsoft@cn.mrs'
    path-in-bundle: 'geo/geosite/microsoft@cn.mrs'

  geolocation-cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/geolocation-cn.mrs'
    path: './ruleset/geolocation-cn.mrs'
    path-in-bundle: 'geo/geosite/geolocation-cn.mrs'

  cn_ip:
    <<: *rule_providers_ip
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geoip/cn.mrs'
    path: './ruleset/cn_ip.mrs'
    path-in-bundle: 'geo/geoip/cn.mrs'

  # --- 代理规则集 ---
  
  youtube:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/youtube.mrs'
    path: './ruleset/youtube.mrs'
    path-in-bundle: 'geo/geosite/youtube.mrs'

  googlefcm:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/googlefcm.mrs'
    path: './ruleset/googlefcm.mrs'
    path-in-bundle: 'geo/geosite/googlefcm.mrs'

  google:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/google.mrs'
    path: './ruleset/google.mrs'
    path-in-bundle: 'geo/geosite/google.mrs'

  google_ip:
    <<: *rule_providers_ip
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geoip/google.mrs'
    path: './ruleset/google_ip.mrs'
    path-in-bundle: 'geo/geoip/google.mrs'

  ai:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/category-ai-!cn.mrs'
    path: './ruleset/ai.mrs'
    path-in-bundle: 'geo/geosite/category-ai-!cn.mrs'

  telegram:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/telegram.mrs'
    path: './ruleset/telegram.mrs'
    path-in-bundle: 'geo/geosite/telegram.mrs'

  telegram_ip:
    <<: *rule_providers_ip
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geoip/telegram.mrs'
    path: './ruleset/telegram_ip.mrs'
    path-in-bundle: 'geo/geoip/telegram.mrs'


  twitter:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/twitter.mrs'
    path: './ruleset/twitter.mrs'
    path-in-bundle: 'geo/geosite/twitter.mrs'

  twitter_ip:
    <<: *rule_providers_ip
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geoip/twitter.mrs'
    path: './ruleset/twitter_ip.mrs'
    path-in-bundle: 'geo/geoip/twitter.mrs'

  geolocation-!cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/geolocation-!cn.mrs'
    path: './ruleset/geolocation-!cn.mrs'
    path-in-bundle: 'geo/geosite/geolocation-!cn.mrs'

  # --- 其他规则集 ---
  adblockmihomolite:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockmihomolite.mrs'
    path: './ruleset/adblockmihomolite.mrs'
    path-in-bundle: 'geo/geosite/category-ads-all.mrs'

  cn_additional:
    <<: *rule_providers_domain
    url: 'https://static-file-global.353355.xyz/rules/cn-additional-list.mrs'
    path: './ruleset/cn-additional-list.mrs'
    path-in-bundle: 'geo/geosite/cn.mrs'

  cn:
    <<: *rule_providers_domain
    url: 'https://fastly.jsdelivr.net/gh/appshubcc/bett-rules@meta/geo/geosite/cn.mrs'
    path: './ruleset/cn.mrs'
    path-in-bundle: 'geo/geosite/cn.mrs'
  # --- Fake IP 过滤 ---
  fakeipfilter_cn: 
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: 'https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/rules/fakeipfilter-cn.list'
    path: './ruleset/fakeipfilter-cn.list'

  fakeipfilter_!cn:
    type: http
    interval: 86400
    behavior: domain
    format: text
    url: 'https://raw.githubusercontent.com/qichiyuhub/rule/refs/heads/main/rules/fakeipfilter-!cn.list'
    path: './ruleset/fakeipfilter-!cn.list'

