[custom]

;=========================================================
; SubConverter_config Full rules
; 
; Author: RikkaSaiko1
; Project: https://github.com/RikkaSaiko1/clash_config
; 
; Based on:
; Author: ACL4SSR
; Project: https://github.com/ACL4SSR/ACL4SSR
;
; Author: appshubcc
; Project: https://github.com/appshubcc/bett-rules
; 
; Author: AIsouler
; Project: https://github.com/AIsouler/MyClash
;=========================================================


; DIRECT rulesets
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/private.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/cn.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/fakeip-filter.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/geolocation-cn.list
; Download DIRECT
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
; Custom Direct
ruleset=DIRECT,[]DOMAIN,fsend.cn
ruleset=DIRECT,[]DOMAIN,international-gfe.download.nvidia.com


; AdBlock
ruleset=🛑 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

; Google / FCM
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/google@cn.list
ruleset=🌐 Google,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/googlefcm.list
ruleset=🌐 Google,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/google.list

; Telegram
ruleset=📲 Telegram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/telegram.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/telegram.list

; AI
ruleset=🤖 AI,https://raw.githubusercontent.com/appshubcc/bett-rules/refs/heads/meta/geo/geosite/category-ai-!cn.list

; YouTube
ruleset=▶️ YouTube,https://raw.githubusercontent.com/appshubcc/bett-rules/refs/heads/meta/geo/geosite/youtube.list

; Microsoft
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/bing.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/onedrive.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/microsoft.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/microsoft.list

; Apple
ruleset=🍎 Apple,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/apple.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/apple.list

; Steam
ruleset=🎮 Steam,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/steam.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/steam.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/steam@cn.list

; TikTok
ruleset=🎵 TikTok,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/tiktok.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/tiktok.list

; Twitter
ruleset=🐦 Twitter,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/twitter.list
ruleset=🐦 Twitter,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/twitter.list

; Instagram
ruleset=📷 Instagram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/instagram.list


; Netflix
ruleset=🎬 Netflix,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/netflix.list
ruleset=🎬 Netflix,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/netflix.list

; Emby
ruleset=📺 Emby,https://raw.githubusercontent.com/appshubcc/bett-rules/refs/heads/meta/geo/geosite/category-emby.list
ruleset=📺 Emby,[]DOMAIN-SUFFIX,mb3admin.com
ruleset=📺 Emby,[]DOMAIN-SUFFIX,nubebelle.com
ruleset=📺 Emby,[]DOMAIN-KEYWORD,emby
ruleset=📺 Emby,[]PROCESS-NAME,com.mb.android
ruleset=📺 Emby,[]PROCESS-NAME,tv.emby.embyatv
ruleset=📺 Emby,[]PROCESS-NAME,com.hush.yamby
ruleset=📺 Emby,[]PROCESS-NAME,com.feifeiduck.capyplayer
ruleset=📺 Emby,[]PROCESS-NAME,com.mountains.hills
ruleset=📺 Emby,[]PROCESS-NAME,RodelPlayer.App.exe

; PikPak
ruleset=☁️ PikPak,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/pikpak.list

; Spotify
ruleset=🎵 Spotify,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/spotify.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/spotify.list

; Crypto
ruleset=₿ Crypto,https://raw.githubusercontent.com/appshubcc/bett-rules/refs/heads/meta/geo/geosite/category-cryptocurrency.list

; EHentai
ruleset=🔞 EHentai,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/ehentai.list

; GFW / GitHub
ruleset=🚀 PROXY,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/gfw.list
ruleset=🚀 PROXY,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/github.list

; dns
ruleset=🚀 PROXY,https://raw.githubusercontent.com/xishang0128/rules/main/clash%20or%20stash/prevent_dns_leak/prevent_dns_leak_domain.list

; China Direct
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/cn.list
ruleset=DIRECT,[]GEOIP,CN

; Final
ruleset=🚀 PROXY,[]FINAL

;=========================================================
; Service Groups
;=========================================================

; PROXY GROUPS
custom_proxy_group=🚀 PROXY`select`.*`[]♻️ AUTO`[]🇭🇰 HK`[]🇯🇵 JP`[]🇺🇸 US`[]🇸🇬 SG`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

custom_proxy_group=♻️ AUTO`url-test`.*`https://www.apple.com/library/test/success.html`600,,50

; AI
custom_proxy_group=🤖 AI`select`[]🇺🇸 US`[]🚀 PROXY`[]🇸🇬 SG`[]🇯🇵 JP`[]🇰🇷 KR

; Google FCM
; custom_proxy_group=📢 Google FCM`select`[]DIRECT`[]🚀 PROXY`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; YouTube
custom_proxy_group=▶️ YouTube`select`[]🚀 PROXY`[]♻️ AUTO`[]🇸🇬 SG`[]🇭🇰 HK`[]🇹🇼 TW`[]🇯🇵 JP`[]🇺🇸 US`[]🇰🇷 KR`[]🌐 Other`[]DIRECT

; Google
custom_proxy_group=🌐 Google`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other`[]DIRECT


; Microsoft
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; Apple
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; Telegram
custom_proxy_group=📲 Telegram`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other`[]DIRECT

; Steam
custom_proxy_group=🎮 Steam`select`[]DIRECT`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; TikTok
custom_proxy_group=🎵 TikTok`select`[]🇯🇵 JP`[]🚀 PROXY`[]♻️ AUTO`[]🇭🇰 HK`[]🇺🇸 US`[]🇸🇬 SG`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; Twitter
custom_proxy_group=🐦 Twitter`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; Instagram
custom_proxy_group=📷 Instagram`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; Netflix
custom_proxy_group=🎬 Netflix`select`[]🇺🇸 US`[]🚀 PROXY`[]♻️ AUTO`[]🇭🇰 HK`[]🇯🇵 JP`[]🇸🇬 SG`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other`[]DIRECT

; Emby
custom_proxy_group=📺 Emby`select`[]DIRECT`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; PikPak
custom_proxy_group=☁️ PikPak`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other`[]DIRECT

; Spotify
custom_proxy_group=🎵 Spotify`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other`[]DIRECT

; Crypto
custom_proxy_group=₿ Crypto`select`[]🇯🇵 JP`[]🚀 PROXY`[]♻️ AUTO`[]🇭🇰 HK`[]🇺🇸 US`[]🇸🇬 SG`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; EHentai
custom_proxy_group=🔞 EHentai`select`[]🇺🇸 US`[]🚀 PROXY`[]♻️ AUTO`[]🇭🇰 HK`[]🇯🇵 JP`[]🇸🇬 SG`[]🇹🇼 TW`[]🇰🇷 KR`[]🌐 Other

; AdBlock
custom_proxy_group=🛑 AdBlock`select`[]REJECT`[]REJECT-DROP`[]PASS`[]DIRECT

;=========================================================
; Region Groups
;=========================================================

; Hong Kong
custom_proxy_group=🇭🇰 HK`select`(港|HK|hk|Hong Kong|HongKong|hongkong)

; Japan
custom_proxy_group=🇯🇵 JP`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)

; United States
custom_proxy_group=🇺🇸 US`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)

; Taiwan
custom_proxy_group=🇹🇼 TW`select`(台|新北|彰化|TW|Taiwan)

; Singapore
custom_proxy_group=🇸🇬 SG`select`(新加坡|坡|狮城|SG|Singapore)

; South Korea
custom_proxy_group=🇰🇷 KR`select`(KR|Korea|KOR|首尔|韩|韓)

; Other
; 除 HK / JP / US / TW / SG / KR 外的其他节点
custom_proxy_group=🌐 Other`select`^(?!.*(港|HK|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|KR|Korea|KOR|首尔|韩|韓)).*$`


enable_rule_generator=true
overwrite_original_rules=true