[custom]

;=========================================================
; SubConverter_config lite rules
; 
; Author: RikkaSaiko1
; Project: https://github.com/RikkaSaiko1/clash_config
; 
; Based on:
; Author: ACL4SSR
; Project: https://github.com/ACL4SSR/ACL4SSR
;
; Author: appshubcc
; Project: https://github.com/appshubcc/bett-rules
; 
; Author: AIsouler
; Project: https://github.com/AIsouler/MyClash
;=========================================================


; DIRECT rulesets
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/private.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/cn.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/fakeip-filter.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/geolocation-cn.list
; Download DIRECT
; ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
; Custom Direct
ruleset=DIRECT,[]DOMAIN,fsend.cn
ruleset=DIRECT,[]DOMAIN,international-gfe.download.nvidia.com

; Google / FCM
ruleset=🌐 Google,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/googlefcm.list
ruleset=🌐 Google,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/google.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/google@cn.list

; Telegram
ruleset=📲 Telegram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/telegram.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/telegram.list

; AI
ruleset=🤖 AI,https://raw.githubusercontent.com/appshubcc/bett-rules/refs/heads/meta/geo/geosite/category-ai-!cn.list

; YouTube
ruleset=▶️ YouTube,https://raw.githubusercontent.com/appshubcc/bett-rules/refs/heads/meta/geo/geosite/youtube.list

ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/steam@cn.list

; Twitter
ruleset=🐦 Twitter,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/twitter.list
ruleset=🐦 Twitter,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/twitter.list

; dns
ruleset=🚀 PROXY,https://raw.githubusercontent.com/xishang0128/rules/main/clash%20or%20stash/prevent_dns_leak/prevent_dns_leak_domain.list

; China Direct
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/cn.list
ruleset=DIRECT,[]GEOIP,CN

; Final
ruleset=🚀 PROXY,[]FINAL

;=========================================================
; Service Groups
;=========================================================

; PROXY GROUPS
custom_proxy_group=🚀 PROXY`select`.*`[]♻️ AUTO`[]🇭🇰 HK AUTO`[]🇯🇵 JP AUTO`[]🇺🇸 US AUTO`[]🇸🇬 SG AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other AUTO

custom_proxy_group=♻️ AUTO`url-test`.*`https://www.apple.com/library/test/success.html`300,5,50

; AI
custom_proxy_group=🤖 AI`select`[]🇺🇸 US AUTO`[]🚀 PROXY`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇰🇷 KR AUTO

; YouTube
custom_proxy_group=▶️ YouTube`select`[]🚀 PROXY`[]♻️ AUTO`[]🇸🇬 SG AUTO`[]🇭🇰 HK AUTO`[]🇹🇼 TW AUTO`[]🇯🇵 JP AUTO`[]🇺🇸 US AUTO`[]🇰🇷 KR AUTO`[]🌐 Other AUTO`[]DIRECT

; Google
custom_proxy_group=🌐 Google`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other AUTO`[]DIRECT

; Telegram
custom_proxy_group=📲 Telegram`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other AUTO`[]DIRECT

; Twitter
custom_proxy_group=🐦 Twitter`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other AUTO

;=========================================================
; Region Groups
;=========================================================

; Hong Kong
custom_proxy_group=🇭🇰 HK AUTO`url-test`.*(港|(?<![A-Za-z])HK(?![A-Za-z])|hk|Hong Kong|HongKong|hongkong)`https://www.apple.com/library/test/success.html`300,5,50

; Japan
custom_proxy_group=🇯🇵 JP AUTO`url-test`.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<![A-Za-z])JP(?![A-Za-z])|Japan)`https://www.apple.com/library/test/success.html`300,5,50

; United States
custom_proxy_group=🇺🇸 US AUTO`url-test`.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(?<![A-Za-z])US(?![A-Za-z])|United States)`https://www.apple.com/library/test/success.html`300,5,50

; Taiwan
custom_proxy_group=🇹🇼 TW AUTO`url-test`.*(台|新北|彰化|(?<![A-Za-z])TW(?![A-Za-z])|Taiwan)`https://www.apple.com/library/test/success.html`300,5,50

; Singapore
custom_proxy_group=🇸🇬 SG AUTO`url-test`.*(新加坡|狮城|(?<![A-Za-z])SG(?![A-Za-z])|Singapore)`https://www.apple.com/library/test/success.html`300,5,50

; South Korea
custom_proxy_group=🇰🇷 KR AUTO`url-test`.*((?<![A-Za-z])KR(?![A-Za-z])|Korea|KOR|首尔|韩|韓)`https://www.apple.com/library/test/success.html`300,5,50

; Other
; 除 HK / JP / US / TW / SG / KR 外的其他节点
custom_proxy_group=🌐 Other AUTO`url-test`^(?!.*(港|(?<![A-Za-z])HK(?![A-Za-z])|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<![A-Za-z])JP(?![A-Za-z])|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(?<![A-Za-z])US(?![A-Za-z])|United States|台|新北|彰化|(?<![A-Za-z])TW(?![A-Za-z])|Taiwan|新加坡|坡|狮城|(?<![A-Za-z])SG(?![A-Za-z])|Singapore|(?<![A-Za-z])KR(?![A-Za-z])|Korea|KOR|首尔|韩|韓)).*$`https://www.apple.com/library/test/success.html`300,5,50


enable_rule_generator=true
overwrite_original_rules=true