[custom]

;=========================================================
; SubConverter_config Full rules
; 
; Author: RikkaSaiko1
; Project: https://github.com/RikkaSaiko1/clash_config
; 
; Based on:
; Author: ACL4SSR
; Project: https://github.com/ACL4SSR/ACL4SSR
;
; Author: appshubcc
; Project: https://github.com/appshubcc/bett-rules
; 
; Author: AIsouler
; Project: https://github.com/AIsouler/MyClash
;=========================================================


; DIRECT rulesets
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/private.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/fakeip-filter.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/geolocation-cn.list
; Custom Direct
ruleset=DIRECT,[]DOMAIN,fsend.cn
ruleset=DIRECT,[]DOMAIN,international-gfe.download.nvidia.com


; AdBlock
ruleset=🛑 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

; YouTube
ruleset=▶️ YouTube,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/youtube.list

; Google / FCM
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/googlefcm.list
ruleset=🌐 Google,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/google.list
ruleset=🌐 Google,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/google-play.list
; ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/google@cn.list

; Telegram
ruleset=📲 Telegram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/telegram.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/telegram.list

; AI
ruleset=🤖 AI,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/category-ai-!cn.list

; Microsoft
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/bing.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/onedrive.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/microsoft.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/microsoft.list

; Apple
ruleset=🍎 Apple,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/apple.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/apple.list

; Steam
ruleset=🎮 Steam,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/steam.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/steam.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/steam@cn.list

; TikTok
ruleset=🎵 TikTok,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/tiktok.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/tiktok.list

; Twitter
ruleset=🐦 Twitter,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/twitter.list
ruleset=🐦 Twitter,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/twitter.list

; Instagram
ruleset=📷 Instagram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/instagram.list

; Netflix
ruleset=🎬 Netflix,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/netflix.list
ruleset=🎬 Netflix,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/netflix.list

; Emby
ruleset=📺 Emby,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/category-emby.list
ruleset=📺 Emby,[]DOMAIN-SUFFIX,mb3admin.com
ruleset=📺 Emby,[]DOMAIN-SUFFIX,nubebelle.com
ruleset=📺 Emby,[]DOMAIN-KEYWORD,emby
ruleset=📺 Emby,[]PROCESS-NAME,com.mb.android
ruleset=📺 Emby,[]PROCESS-NAME,tv.emby.embyatv
ruleset=📺 Emby,[]PROCESS-NAME,com.hush.yamby
ruleset=📺 Emby,[]PROCESS-NAME,com.feifeiduck.capyplayer
ruleset=📺 Emby,[]PROCESS-NAME,com.mountains.hills
ruleset=📺 Emby,[]PROCESS-NAME,RodelPlayer.App.exe

; PikPak
ruleset=☁️ PikPak,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/pikpak.list

; Spotify
ruleset=🎵 Spotify,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/spotify.list
ruleset=🎵 Spotify,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/spotify.list

; Crypto
ruleset=₿ Crypto,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/category-cryptocurrency.list

; EHentai
ruleset=🔞 EHentai,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/ehentai.list

; GFW / GitHub
ruleset=🚀 PROXY,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/gfw.list
ruleset=🚀 PROXY,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/classical/github.list

; dns
; ruleset=🚀 PROXY,https://raw.githubusercontent.com/xishang0128/rules/main/clash%20or%20stash/prevent_dns_leak/prevent_dns_leak_domain.list

; China Direct
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/classical/cn.list
ruleset=DIRECT,[]GEOIP,CN

; Final
ruleset=🚀 PROXY,[]FINAL

;=========================================================
; Service Groups
;=========================================================

; PROXY GROUPS
custom_proxy_group=🚀 PROXY`select`.*`[]♻️ AUTO`[]🇭🇰 HK AUTO`[]🇯🇵 JP AUTO`[]🇺🇸 US AUTO`[]🇸🇬 SG AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

custom_proxy_group=♻️ AUTO`url-test`.*`https://www.apple.com/library/test/success.html`300,5,50

; AI
custom_proxy_group=🤖 AI`select`[]🇺🇸 US AUTO`[]🚀 PROXY`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇰🇷 KR AUTO

; Google FCM
; custom_proxy_group=📢 Google FCM`select`[]DIRECT`[]🚀 PROXY`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; YouTube
custom_proxy_group=▶️ YouTube`select`[]🚀 PROXY`[]♻️ AUTO`[]🇸🇬 SG AUTO`[]🇭🇰 HK AUTO`[]🇹🇼 TW AUTO`[]🇯🇵 JP AUTO`[]🇺🇸 US AUTO`[]🇰🇷 KR AUTO`[]🌐 Other`[]DIRECT

; Google
custom_proxy_group=🌐 Google`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other`[]DIRECT


; Microsoft
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; Apple
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; Telegram
custom_proxy_group=📲 Telegram`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other`[]DIRECT

; Steam
custom_proxy_group=🎮 Steam`select`[]DIRECT`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; TikTok
custom_proxy_group=🎵 TikTok`select`[]🇯🇵 JP AUTO`[]🚀 PROXY`[]♻️ AUTO`[]🇭🇰 HK AUTO`[]🇺🇸 US AUTO`[]🇸🇬 SG AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; Twitter
custom_proxy_group=🐦 Twitter`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; Instagram
custom_proxy_group=📷 Instagram`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; Netflix
custom_proxy_group=🎬 Netflix`select`[]🇺🇸 US AUTO`[]🚀 PROXY`[]♻️ AUTO`[]🇭🇰 HK AUTO`[]🇯🇵 JP AUTO`[]🇸🇬 SG AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other`[]DIRECT

; Emby
custom_proxy_group=📺 Emby`select`[]DIRECT`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; PikPak
custom_proxy_group=☁️ PikPak`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other`[]DIRECT

; Spotify
custom_proxy_group=🎵 Spotify`select`[]🚀 PROXY`[]♻️ AUTO`[]🇺🇸 US AUTO`[]🇭🇰 HK AUTO`[]🇸🇬 SG AUTO`[]🇯🇵 JP AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other`[]DIRECT

; Crypto
custom_proxy_group=₿ Crypto`select`[]🇯🇵 JP AUTO`[]🚀 PROXY`[]♻️ AUTO`[]🇭🇰 HK AUTO`[]🇺🇸 US AUTO`[]🇸🇬 SG AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; EHentai
custom_proxy_group=🔞 EHentai`select`[]🇺🇸 US AUTO`[]🚀 PROXY`[]♻️ AUTO`[]🇭🇰 HK AUTO`[]🇯🇵 JP AUTO`[]🇸🇬 SG AUTO`[]🇹🇼 TW AUTO`[]🇰🇷 KR AUTO`[]🌐 Other

; AdBlock
custom_proxy_group=🛑 AdBlock`select`[]REJECT`[]PASS`[]DIRECT

;=========================================================
; Region Groups
;=========================================================

; Hong Kong
custom_proxy_group=🇭🇰 HK AUTO`url-test`.*(港|(?<![A-Za-z])HK(?![A-Za-z])|hk|Hong Kong|HongKong|hongkong)`https://www.apple.com/library/test/success.html`300,5,50

; Japan
custom_proxy_group=🇯🇵 JP AUTO`url-test`.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<![A-Za-z])JP(?![A-Za-z])|Japan)`https://www.apple.com/library/test/success.html`300,5,50

; United States
custom_proxy_group=🇺🇸 US AUTO`url-test`.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(?<![A-Za-z])US(?![A-Za-z])|United States)`https://www.apple.com/library/test/success.html`300,5,50

; Taiwan
custom_proxy_group=🇹🇼 TW AUTO`url-test`.*(台|新北|彰化|(?<![A-Za-z])TW(?![A-Za-z])|Taiwan)`https://www.apple.com/library/test/success.html`300,5,50

; Singapore
custom_proxy_group=🇸🇬 SG AUTO`url-test`.*(新加坡|狮城|(?<![A-Za-z])SG(?![A-Za-z])|Singapore)`https://www.apple.com/library/test/success.html`300,5,50

; South Korea
custom_proxy_group=🇰🇷 KR AUTO`url-test`.*((?<![A-Za-z])KR(?![A-Za-z])|Korea|KOR|首尔|韩|韓)`https://www.apple.com/library/test/success.html`300,5,50

; Other
; 除 HK / JP / US / TW / SG / KR 外的其他节点
custom_proxy_group=🌐 Other`url-test`^(?!.*(港|(?<![A-Za-z])HK(?![A-Za-z])|hk|Hong Kong|HongKong|hongkong|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<![A-Za-z])JP(?![A-Za-z])|Japan|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(?<![A-Za-z])US(?![A-Za-z])|United States|台|新北|彰化|(?<![A-Za-z])TW(?![A-Za-z])|Taiwan|新加坡|坡|狮城|(?<![A-Za-z])SG(?![A-Za-z])|Singapore|(?<![A-Za-z])KR(?![A-Za-z])|Korea|KOR|首尔|韩|韓)).*$`https://www.apple.com/library/test/success.html`300,5,50


enable_rule_generator=true
overwrite_original_rules=true